### ISSUE TITLE
Document model Editor Design implementation

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/powerhouse#421]
- Add debounce for saving in document model - document model Save behavior 5 seconds debounced save. Unfocus input field should also trigger a save. 
-  Bring back adding operations with the help of modules
- Update the previous functionality where possible with elements from the new wireframe. 

![Image](https://github.com/user-attachments/assets/1bd98f07-e150-4800-9c53-aef90854f02c)

**Comment by gpuente** [comment]
Duplicated: https://github.com/powerhouse-inc/powerhouse/issues/247
